### PR TITLE
feat: smart events SDK

### PR DESCRIPTION
**Pull request by wtrocki**
This PR will enable generation of smart events SDK

### CODE REVIEW

**Comment by wtrocki** [comment]
Note: no example provided as there is no mock support for smart events (subject to discussion with their team)

**Comment by wtrocki** [comment]
Ready for review.

**Comment by wtrocki** [comment]
When reviewing - ignore second commit which is generated code.

**Comment by wtrocki** [comment]
We do provide SDK as it is for now as I'm investigating using different generator that will invalidate examples etc.

**Comment by dimakis** [comment]
So the main bulk of this happens in the generate.sh script right?
question, where is the smartevents openapi file coming from? It's pulled from here `PACKAGE_NAME="com.openshift.cloud.api.smartevents"`?

**Comment by wtrocki** [comment]
> question, where is the smartevents openapi file coming from? It's pulled from here PACKAGE_NAME="com.openshift.cloud.api.smartevents"?


I have shared with you our process in the google doc. We need it documented upstream later phase (once we settle with better way)

**Pull request merged**
