### PR TITLE
feat: generate errors SDK for java

### PR DESCRIPTION
**Pull request by wtrocki**
## How this works

1. Error codes are generated as 3th job due to additional timing needed for QA to pickup error updates.
2. Error codes are generated only on API change due to fact that we agreed with teams to change openapi when errors are changed. This is simpler rather than constraining team to have all errors in the single file.
3. Once Job is triggered we fetch all APIs 

## Notes

COS api is not on stage yet but I have added it manually to provide early support.
Solution provided is dedicated to this SDK. Other SDKS will use different patterns.

## Verification

Will work with @riccardo-forina to replace existing error codes and use SDK once merged.

### CODE REVIEW

**Comment by wtrocki** [comment]
I still need to tune generation to work properly. 

Other SDK work: https://github.com/redhat-developer/app-services-sdk-js/pull/252

**Comment by wtrocki** [comment]
I need to add examples etc. but looking for initial review

**Comment by wtrocki** [comment]
@secondsun pinging again (in case it was lost in inbox). I would like to ask for review for that PR

**Comment by secondsun** [comment]
Can you add the generate errors script to the makefile or the generate script? right now make will delete the errors and not recreate them

**Pull request merged**
